version: "3.7"
volumnes:
        postgres_data:
services:
  postgres:
    # Aquí estaremos agregando las configuración del servicio de postgres
          image: postgres:11-alpine
          ports: 
                   - "5432:5432" 
          volumes:
                  - "postgres_data:/usr/to/where/postgres/stores/data"
          environment:
                   POSTGRES_PASSWORD: "example"
        
